# -*- coding: utf-8 -*-
"""AmaliTech_Market_Gap_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqRwxSJzK68tQU7KMyR-HQZTOZzcl2eo
"""

# ============================================================
# AMALITECH CAPSTONE CHALLENGE — THE SUGAR TRAP
# Market Gap Analysis — Open Food Facts Dataset
# Analyst: Lawrence Koomson | UCC | June 2026
# Client: Helix CPG Partners
# ============================================================

# CELL 1: Install and Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
import re
from collections import Counter
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', 100)
plt.style.use('seaborn-v0_8')

print("✅ All libraries imported successfully!")
print("🚀 AmaliTech Capstone — The Sugar Trap Market Gap Analysis")
print("👤 Analyst: Lawrence Koomson | UCC 2026")

# ============================================================
# CELL 2: Data Ingestion — Load Open Food Facts Dataset
# Loading first 500,000 rows as instructed
# ============================================================

# Key columns we need for this analysis
COLS_NEEDED = [
    'product_name',
    'categories_tags',
    'sugars_100g',
    'proteins_100g',
    'fat_100g',
    'fiber_100g',
    'energy_100g',
    'ingredients_text',
    'nutriscore_score',
    'countries_tags'
]

print("⏳ Loading dataset — please wait, this may take 2-3 minutes...")

# Load directly from Open Food Facts URL
# Using tab separator as specified in their documentation
url = "https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz"

df_raw = pd.read_csv(
    url,
    sep='\t',                    # Tab separated
    nrows=500000,                # First 500,000 rows as instructed
    usecols=lambda c: c in COLS_NEEDED,  # Only load columns we need
    low_memory=False,
    encoding='utf-8',
    on_bad_lines='skip'          # Skip any malformed rows
)

print(f"✅ Dataset loaded successfully!")
print(f"📊 Shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")
print(f"\nColumns loaded:")
print(df_raw.columns.tolist())
print(f"\nFirst 3 rows:")
df_raw.head(3)

# ============================================================
# CELL 3: Exploratory Data Analysis (EDA)
# Understanding the raw dataset structure
# ============================================================

print("=" * 60)
print("    EXPLORATORY DATA ANALYSIS — OPEN FOOD FACTS")
print("=" * 60)

# 1. Dataset shape
print(f"\n📊 Dataset Shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")

# 2. Data types
print(f"\n📋 Data Types:")
print(df_raw.dtypes)

# 3. Missing values analysis
print(f"\n🔍 Missing Values Report:")
missing = df_raw.isnull().sum()
missing_pct = (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
missing_report = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_pct
}).sort_values('Missing %', ascending=False)
print(missing_report)

# 4. Statistical summary of nutritional columns
print(f"\n📈 Nutritional Columns Statistical Summary:")
nutrition_cols = ['sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g', 'energy_100g']
print(df_raw[nutrition_cols].describe().round(2))

# 5. Sample of categories_tags
print(f"\n🏷️ Sample of categories_tags column:")
sample_cats = df_raw['categories_tags'].dropna().head(10)
for i, cat in enumerate(sample_cats):
    print(f"  {i+1}. {str(cat)[:100]}")

# 6. How many products have both sugar and protein data
both_data = df_raw[['sugars_100g', 'proteins_100g']].dropna()
print(f"\n✅ Products with BOTH sugar and protein data: {len(both_data):,}")
print(f"   ({len(both_data)/len(df_raw)*100:.1f}% of total dataset)")

# 7. Products with categories
has_categories = df_raw['categories_tags'].notna().sum()
print(f"✅ Products with categories_tags: {has_categories:,}")
print(f"   ({has_categories/len(df_raw)*100:.1f}% of total dataset)")

print("\n✅ EDA Complete!")

# ============================================================
# CELL 4: Story 1 — Data Ingestion & "The Clean Up"
# Handling missing values and biologically impossible outliers
# ============================================================

print("=" * 60)
print("    STORY 1: DATA INGESTION & THE CLEAN UP")
print("=" * 60)

# Step 1: Start with a copy
df = df_raw.copy()
print(f"\n📊 Starting shape: {df.shape[0]:,} rows")

# Step 2: Drop rows with missing product_name
before = len(df)
df = df[df['product_name'].notna() & (df['product_name'].str.strip() != '')]
print(f"✅ After removing missing product_name: {len(df):,} rows (removed {before - len(df):,})")

# Step 3: Drop rows missing BOTH sugars_100g AND proteins_100g
# (we need at least these two for our core analysis)
before = len(df)
df = df[df['sugars_100g'].notna() & df['proteins_100g'].notna()]
print(f"✅ After removing missing sugar/protein: {len(df):,} rows (removed {before - len(df):,})")

# Step 4: Remove biologically impossible outliers
# Nutritional values per 100g cannot exceed 100g (except energy)
# Sugar: 0-100g per 100g product
# Protein: 0-100g per 100g product
# Fat: 0-100g per 100g product
# Combined macros cannot exceed 100g per 100g

before = len(df)
df = df[
    (df['sugars_100g'] >= 0) & (df['sugars_100g'] <= 100) &
    (df['proteins_100g'] >= 0) & (df['proteins_100g'] <= 100) &
    ((df['fat_100g'].isna()) | ((df['fat_100g'] >= 0) & (df['fat_100g'] <= 100)))
]
print(f"✅ After removing impossible outliers (>100g per 100g): {len(df):,} rows (removed {before - len(df):,})")

# Step 5: Remove rows where sugar + protein + fat > 105g
# (biological impossibility — leaves small margin for rounding)
before = len(df)
df['total_macros'] = (
    df['sugars_100g'].fillna(0) +
    df['proteins_100g'].fillna(0) +
    df['fat_100g'].fillna(0)
)
df = df[df['total_macros'] <= 105]
df = df.drop(columns=['total_macros'])
print(f"✅ After removing macro sum > 105g: {len(df):,} rows (removed {before - len(df):,})")

# Step 6: Fill missing fiber with 0 (fiber not always reported)
df['fiber_100g'] = df['fiber_100g'].fillna(0)

# Step 7: Reset index
df = df.reset_index(drop=True)

print(f"\n{'='*60}")
print(f"🎯 CLEAN DATASET SUMMARY")
print(f"{'='*60}")
print(f"✅ Final clean shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"✅ Missing sugars_100g: {df['sugars_100g'].isna().sum()}")
print(f"✅ Missing proteins_100g: {df['proteins_100g'].isna().sum()}")
print(f"✅ Missing product_name: {df['product_name'].isna().sum()}")
print(f"\n📈 Nutritional Stats After Cleaning:")
print(df[['sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g']].describe().round(2))

# Visualize distributions
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Distribution of Sugar vs Protein (Clean Data)', fontsize=14, fontweight='bold')

axes[0].hist(df['sugars_100g'], bins=50, color='#E74C3C', alpha=0.7, edgecolor='white')
axes[0].set_title('Sugar per 100g Distribution')
axes[0].set_xlabel('Sugar (g per 100g)')
axes[0].set_ylabel('Product Count')

axes[1].hist(df['proteins_100g'], bins=50, color='#2ECC71', alpha=0.7, edgecolor='white')
axes[1].set_title('Protein per 100g Distribution')
axes[1].set_xlabel('Protein (g per 100g)')
axes[1].set_ylabel('Product Count')

plt.tight_layout()
plt.savefig('story1_distributions.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ Story 1 — Data Cleaning COMPLETE!")
print(f"✅ Chart saved as story1_distributions.png")

# ============================================================
# CELL 5: Story 2 — The Category Wrangler
# Parsing categories_tags and creating 5+ high-level buckets
# ============================================================

print("=" * 60)
print("    STORY 2: THE CATEGORY WRANGLER")
print("=" * 60)

def assign_primary_category(tags_str):
    """
    Parse categories_tags string and assign a high-level
    Primary Category based on keyword matching.
    Returns one of 7 distinct high-level category buckets.
    """
    if pd.isna(tags_str) or str(tags_str).strip() == '':
        return 'Uncategorized'

    tags = str(tags_str).lower()

    # Priority order matters — more specific first
    # Bucket 1: Proteins & Supplements
    if any(kw in tags for kw in [
        'protein', 'supplement', 'bodybuilding', 'whey',
        'sport', 'fitness', 'muscle', 'energy-drink',
        'energy-bar', 'protein-bar'
    ]):
        return 'Proteins & Supplements'

    # Bucket 2: Dairy & Eggs
    if any(kw in tags for kw in [
        'dairy', 'milk', 'cheese', 'yogurt', 'yoghurt',
        'cream', 'butter', 'egg', 'fromage', 'lait'
    ]):
        return 'Dairy & Eggs'

    # Bucket 3: Snacks & Confectionery
    if any(kw in tags for kw in [
        'snack', 'biscuit', 'cookie', 'cake', 'candy',
        'chocolate', 'sweet', 'confectionery', 'chips',
        'crisps', 'popcorn', 'wafer', 'cracker', 'dessert'
    ]):
        return 'Snacks & Confectionery'

    # Bucket 4: Beverages
    if any(kw in tags for kw in [
        'beverage', 'drink', 'juice', 'water', 'soda',
        'coffee', 'tea', 'smoothie', 'wine', 'beer',
        'alcohol', 'soft-drink', 'mineral-water'
    ]):
        return 'Beverages'

    # Bucket 5: Meals & Grains
    if any(kw in tags for kw in [
        'meal', 'bread', 'pasta', 'rice', 'grain',
        'cereal', 'flour', 'pizza', 'sandwich', 'soup',
        'sauce', 'condiment', 'spread', 'prepared', 'frozen'
    ]):
        return 'Meals & Grains'

    # Bucket 6: Fruits & Vegetables
    if any(kw in tags for kw in [
        'fruit', 'vegetable', 'plant-based', 'vegan',
        'salad', 'nut', 'seed', 'legume', 'bean',
        'dried-fruit', 'nuts', 'peanut'
    ]):
        return 'Fruits, Nuts & Vegetables'

    # Bucket 7: Meat, Fish & Seafood
    if any(kw in tags for kw in [
        'meat', 'fish', 'seafood', 'chicken', 'beef',
        'pork', 'turkey', 'salmon', 'tuna', 'shrimp',
        'sausage', 'ham', 'bacon'
    ]):
        return 'Meat, Fish & Seafood'

    return 'Other Foods'

# Apply category assignment
print("\n⏳ Assigning primary categories...")
df['primary_category'] = df['categories_tags'].apply(assign_primary_category)

# Results
print("✅ Categories assigned!")
print(f"\n📊 Category Distribution:")
cat_counts = df['primary_category'].value_counts()
cat_pct = (df['primary_category'].value_counts(normalize=True) * 100).round(1)
cat_summary = pd.DataFrame({
    'Count': cat_counts,
    'Percentage': cat_pct
})
print(cat_summary)

# How many products are categorized vs uncategorized
categorized = df[df['primary_category'] != 'Uncategorized'].shape[0]
print(f"\n✅ Categorized products: {categorized:,} ({categorized/len(df)*100:.1f}%)")
print(f"⚠️ Uncategorized: {len(df)-categorized:,} ({(len(df)-categorized)/len(df)*100:.1f}%)")

# Visualize category distribution
fig, ax = plt.subplots(figsize=(12, 6))
colors = ['#E74C3C', '#3498DB', '#2ECC71', '#F39C12',
          '#9B59B6', '#1ABC9C', '#E67E22', '#95A5A6']
cat_counts.plot(kind='bar', ax=ax, color=colors[:len(cat_counts)],
                alpha=0.85, edgecolor='white')
ax.set_title('Product Distribution by Primary Category',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Category')
ax.set_ylabel('Number of Products')
ax.tick_params(axis='x', rotation=45)
for i, v in enumerate(cat_counts):
    ax.text(i, v + 200, f'{v:,}', ha='center', fontsize=9, fontweight='bold')
plt.tight_layout()
plt.savefig('story2_categories.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✅ Story 2 — Category Wrangler COMPLETE!")
print(f"✅ {df['primary_category'].nunique()} distinct high-level categories created")

# ============================================================
# CELL 6: Story 3 — The Nutrient Matrix Visualization
# Sugar (X) vs Protein (Y) Scatter Plot by Category
# Identifying the "Empty Quadrant" — High Protein + Low Sugar
# ============================================================

print("=" * 60)
print("    STORY 3: THE NUTRIENT MATRIX VISUALIZATION")
print("=" * 60)

# Filter to categorized products only
df_viz = df[df['primary_category'] != 'Uncategorized'].copy()

# Define quadrant thresholds
# Using 75th percentile for "High" classification
sugar_threshold = df_viz['sugars_100g'].quantile(0.75)
protein_threshold = df_viz['proteins_100g'].quantile(0.75)

print(f"\n📊 Quadrant Thresholds:")
print(f"   Sugar threshold (75th percentile): {sugar_threshold:.1f}g per 100g")
print(f"   Protein threshold (75th percentile): {protein_threshold:.1f}g per 100g")

# Assign quadrant labels
def assign_quadrant(row):
    high_sugar = row['sugars_100g'] >= sugar_threshold
    high_protein = row['proteins_100g'] >= protein_threshold
    if high_protein and not high_sugar:
        return 'HIGH PROTEIN + LOW SUGAR\n(The Blue Ocean 🎯)'
    elif high_protein and high_sugar:
        return 'HIGH PROTEIN + HIGH SUGAR'
    elif not high_protein and high_sugar:
        return 'LOW PROTEIN + HIGH SUGAR\n(Oversaturated ⚠️)'
    else:
        return 'LOW PROTEIN + LOW SUGAR'

df_viz['quadrant'] = df_viz.apply(assign_quadrant, axis=1)

print(f"\n📊 Quadrant Distribution:")
print(df_viz['quadrant'].value_counts())

# Create the Nutrient Matrix Scatter Plot
fig, ax = plt.subplots(figsize=(14, 10))

# Color map for categories
categories = df_viz['primary_category'].unique()
color_map = {
    'Proteins & Supplements': '#E74C3C',
    'Dairy & Eggs': '#3498DB',
    'Snacks & Confectionery': '#F39C12',
    'Beverages': '#1ABC9C',
    'Meals & Grains': '#9B59B6',
    'Fruits, Nuts & Vegetables': '#2ECC71',
    'Meat, Fish & Seafood': '#E67E22',
    'Other Foods': '#95A5A6'
}

# Sample for performance (max 15,000 points on scatter)
sample_size = min(15000, len(df_viz))
df_sample = df_viz.sample(sample_size, random_state=42)

# Plot each category
for category in categories:
    mask = df_sample['primary_category'] == category
    subset = df_sample[mask]
    if len(subset) > 0:
        ax.scatter(
            subset['sugars_100g'],
            subset['proteins_100g'],
            c=color_map.get(category, '#95A5A6'),
            label=f"{category} (n={len(df_viz[df_viz['primary_category']==category]):,})",
            alpha=0.4,
            s=20,
            edgecolors='none'
        )

# Add quadrant dividers
ax.axvline(x=sugar_threshold, color='red', linestyle='--',
           linewidth=1.5, alpha=0.7, label=f'Sugar threshold: {sugar_threshold:.1f}g')
ax.axhline(y=protein_threshold, color='green', linestyle='--',
           linewidth=1.5, alpha=0.7, label=f'Protein threshold: {protein_threshold:.1f}g')

# Highlight the Blue Ocean quadrant
from matplotlib.patches import Rectangle
blue_ocean_rect = Rectangle(
    (0, protein_threshold),
    sugar_threshold,
    100 - protein_threshold,
    linewidth=2,
    edgecolor='#27AE60',
    facecolor='#27AE60',
    alpha=0.08,
    label='Blue Ocean Zone 🎯'
)
ax.add_patch(blue_ocean_rect)

# Add quadrant labels
ax.text(sugar_threshold/2, protein_threshold + 3,
        '🎯 BLUE OCEAN\nHigh Protein + Low Sugar',
        ha='center', fontsize=11, fontweight='bold', color='#27AE60',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', alpha=0.8))

ax.text(sugar_threshold + 5, 2,
        '⚠️ OVERSATURATED\nHigh Sugar + Low Protein',
        ha='center', fontsize=9, color='#E74C3C', style='italic')

# Labels and formatting
ax.set_xlabel('Sugar per 100g (g)', fontsize=13, fontweight='bold')
ax.set_ylabel('Protein per 100g (g)', fontsize=13, fontweight='bold')
ax.set_title('The Nutrient Matrix: Sugar vs Protein by Category\n"Finding the Blue Ocean in the Snack Aisle"',
             fontsize=14, fontweight='bold')
ax.set_xlim(0, 100)
ax.set_ylim(0, 100)
ax.legend(bbox_to_anchor=(1.02, 1), loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('story3_nutrient_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# Blue Ocean stats
blue_ocean = df_viz[
    (df_viz['sugars_100g'] < sugar_threshold) &
    (df_viz['proteins_100g'] >= protein_threshold)
]
print(f"\n🎯 BLUE OCEAN PRODUCTS (High Protein + Low Sugar):")
print(f"   Count: {len(blue_ocean):,} products")
print(f"   Avg Sugar: {blue_ocean['sugars_100g'].mean():.1f}g")
print(f"   Avg Protein: {blue_ocean['proteins_100g'].mean():.1f}g")
print(f"\n🏆 Top Categories in Blue Ocean:")
print(blue_ocean['primary_category'].value_counts().head(5))

print(f"\n✅ Story 3 — Nutrient Matrix COMPLETE!")
print(f"✅ Chart saved as story3_nutrient_matrix.png")

# ============================================================
# CELL 7: Story 4 — The Recommendation
# Key Insight Box for the Dashboard
# ============================================================

print("=" * 60)
print("    STORY 4: THE RECOMMENDATION")
print("=" * 60)

# Find the BEST category in the Blue Ocean
blue_ocean = df_viz[
    (df_viz['sugars_100g'] < sugar_threshold) &
    (df_viz['proteins_100g'] >= protein_threshold)
].copy()

# Get top Blue Ocean category
top_blue_ocean_category = blue_ocean['primary_category'].value_counts().index[0]
top_category_data = blue_ocean[blue_ocean['primary_category'] == top_blue_ocean_category]

# BUT — Beverages dominate because of protein drinks
# Let's find the most UNDERSERVED snack-focused category
# (excluding beverages since that's already a known market)
blue_ocean_no_bev = blue_ocean[blue_ocean['primary_category'] != 'Beverages']
best_opportunity = blue_ocean_no_bev['primary_category'].value_counts().index[0]
best_data = blue_ocean_no_bev[blue_ocean_no_bev['primary_category'] == best_opportunity]

# Calculate precise recommendation values
target_protein = round(best_data['proteins_100g'].mean(), 1)
target_sugar = round(best_data['sugars_100g'].mean(), 1)
target_sugar_max = round(best_data['sugars_100g'].quantile(0.75), 1)

# Oversaturated zone analysis
oversaturated = df_viz[
    (df_viz['sugars_100g'] >= sugar_threshold) &
    (df_viz['proteins_100g'] < protein_threshold)
]
top_oversaturated = oversaturated['primary_category'].value_counts().index[0]

print(f"\n🎯 KEY FINDINGS:")
print(f"   Blue Ocean Count: {len(blue_ocean):,} products")
print(f"   Blue Ocean Avg Sugar: {blue_ocean['sugars_100g'].mean():.1f}g")
print(f"   Blue Ocean Avg Protein: {blue_ocean['proteins_100g'].mean():.1f}g")
print(f"\n🏆 BEST OPPORTUNITY CATEGORY: {best_opportunity}")
print(f"   Products in this Blue Ocean segment: {len(best_data):,}")
print(f"   Average Protein: {target_protein}g")
print(f"   Average Sugar: {target_sugar}g")
print(f"   Max Sugar (75th pct): {target_sugar_max}g")
print(f"\n⚠️ Most Oversaturated: {top_oversaturated}")

# Build the Key Insight recommendation
recommendation = f"""
Based on the data, the biggest market opportunity is in
{best_opportunity}, specifically targeting products with
{target_protein}g of protein and less than {target_sugar_max}g of sugar.
"""

print(f"\n{'='*60}")
print(f"📋 KEY INSIGHT BOX (for Dashboard):")
print(f"{'='*60}")
print(recommendation)

# Visualize the recommendation
fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Story 4: Market Gap Recommendation — The Blue Ocean',
             fontsize=14, fontweight='bold')

# Chart 1: Blue Ocean vs Oversaturated comparison
quadrant_data = df_viz['quadrant'].value_counts()
colors_q = ['#27AE60', '#E74C3C', '#3498DB', '#F39C12']
axes[0].bar(
    ['Blue Ocean\n(High Protein\nLow Sugar)',
     'Oversaturated\n(Low Protein\nHigh Sugar)',
     'Balanced\n(Low Both)',
     'Premium\n(High Both)'],
    [len(blue_ocean),
     len(oversaturated),
     len(df_viz[(df_viz['sugars_100g'] < sugar_threshold) &
                (df_viz['proteins_100g'] < protein_threshold)]),
     len(df_viz[(df_viz['sugars_100g'] >= sugar_threshold) &
                (df_viz['proteins_100g'] >= protein_threshold)])],
    color=colors_q, alpha=0.85, edgecolor='white'
)
axes[0].set_title('Market Quadrant Distribution', fontweight='bold')
axes[0].set_ylabel('Number of Products')
for i, v in enumerate([len(blue_ocean), len(oversaturated),
    len(df_viz[(df_viz['sugars_100g']<sugar_threshold)&(df_viz['proteins_100g']<protein_threshold)]),
    len(df_viz[(df_viz['sugars_100g']>=sugar_threshold)&(df_viz['proteins_100g']>=protein_threshold)])]):
    axes[0].text(i, v+100, f'{v:,}', ha='center', fontweight='bold', fontsize=10)

# Chart 2: Top Blue Ocean categories
blue_cat = blue_ocean['primary_category'].value_counts().head(6)
blue_cat.plot(kind='barh', ax=axes[1],
              color='#27AE60', alpha=0.85, edgecolor='white')
axes[1].set_title('Blue Ocean Products by Category\n(High Protein + Low Sugar)',
                  fontweight='bold')
axes[1].set_xlabel('Number of Products')
for i, v in enumerate(blue_cat):
    axes[1].text(v+20, i, f'{v:,}', va='center', fontweight='bold')

plt.tight_layout()
plt.savefig('story4_recommendation.png', dpi=150, bbox_inches='tight')
plt.show()

# Key Insight Box visualization
fig2, ax2 = plt.subplots(figsize=(14, 5))
ax2.axis('off')
insight_text = (
    f'KEY INSIGHT FOR HELIX CPG PARTNERS\n\n'
    f'"Based on the data, the biggest market opportunity is in\n'
    f'{best_opportunity}, specifically targeting products\n'
    f'with {target_protein}g of protein and less than {target_sugar_max}g of sugar."\n\n'
    f'Market Evidence: {len(best_data):,} products already exist in this Blue Ocean space,\n'
    f'yet {len(oversaturated):,} products dominate the oversaturated High Sugar zone.\n'
    f'The gap is clear — consumers demanding healthy options are underserved.'
)
ax2.text(0.5, 0.5, insight_text,
         transform=ax2.transAxes,
         fontsize=13, ha='center', va='center',
         bbox=dict(boxstyle='round,pad=1.0',
                  facecolor='#EBF5FB',
                  edgecolor='#2E86C1',
                  linewidth=3),
         fontweight='normal',
         linespacing=1.8)
ax2.set_title('Dashboard Key Insight Box',
              fontsize=14, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('story4_key_insight_box.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ Story 4 — Recommendation COMPLETE!")
print(f"✅ Charts saved!")

# ============================================================
# CELL 8: Story 5 — The "Hidden Gem"
# Top protein sources in High Protein products
# ============================================================

print("=" * 60)
print("    STORY 5: THE HIDDEN GEM — TOP PROTEIN SOURCES")
print("=" * 60)

# Get high protein products with ingredients text
high_protein = df_viz[
    (df_viz['proteins_100g'] >= protein_threshold) &
    (df_viz['ingredients_text'].notna())
].copy()

print(f"\n📊 High Protein products with ingredients: {len(high_protein):,}")

# Define protein source keywords to search for
protein_keywords = {
    'Whey': ['whey', 'whey protein', 'whey powder'],
    'Peanuts': ['peanut', 'groundnut', 'arachide'],
    'Soy/Soya': ['soy', 'soya', 'soybean', 'soja'],
    'Eggs': ['egg', 'eggs', 'egg white', 'albumin'],
    'Milk/Casein': ['casein', 'milk protein', 'skimmed milk', 'skim milk'],
    'Almonds': ['almond', 'almonds'],
    'Chicken': ['chicken', 'poulet'],
    'Fish': ['fish', 'tuna', 'salmon', 'cod'],
    'Peas': ['pea protein', 'peas', 'pea isolate'],
    'Rice Protein': ['rice protein', 'brown rice protein'],
    'Hemp': ['hemp', 'hemp protein', 'hemp seed'],
    'Beef': ['beef', 'boeuf', 'meat protein']
}

# Count occurrences
protein_counts = {}
for source, keywords in protein_keywords.items():
    count = high_protein['ingredients_text'].str.lower().apply(
        lambda x: any(kw in str(x) for kw in keywords)
    ).sum()
    protein_counts[source] = count

# Sort and display
protein_series = pd.Series(protein_counts).sort_values(ascending=False)
top3 = protein_series.head(3)

print(f"\n🏆 TOP PROTEIN SOURCES IN HIGH-PROTEIN PRODUCTS:")
print(f"{'='*40}")
for rank, (source, count) in enumerate(protein_series.items(), 1):
    pct = count/len(high_protein)*100
    bar = '█' * int(pct/2)
    print(f"  {rank:2}. {source:<15} {count:5,} products ({pct:.1f}%) {bar}")

print(f"\n🥇 TOP 3 PROTEIN SOURCES:")
for i, (source, count) in enumerate(top3.items(), 1):
    print(f"   {i}. {source} — found in {count:,} high-protein products")

# Visualize
fig, ax = plt.subplots(figsize=(12, 7))
colors_p = ['#E74C3C' if i < 3 else '#3498DB'
            for i in range(len(protein_series))]
protein_series.plot(kind='bar', ax=ax, color=colors_p, alpha=0.85, edgecolor='white')
ax.set_title('Hidden Gem: Top Protein Sources in High-Protein Products\n(Red = Top 3)',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Protein Source')
ax.set_ylabel('Number of High-Protein Products Containing This Ingredient')
ax.tick_params(axis='x', rotation=45)
for i, v in enumerate(protein_series):
    ax.text(i, v+10, str(v), ha='center', fontsize=9, fontweight='bold')
plt.tight_layout()
plt.savefig('story5_hidden_gem.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n✅ Story 5 — Hidden Gem COMPLETE!")

# ============================================================
# CELL 9: Story 6 — Candidate's Choice Challenge
# ADDED: Nutri-Score Health Rating Analysis by Category
# JUSTIFICATION: Shows not just WHERE the gap is but HOW
# HEALTHY the Blue Ocean products actually are —
# critical for a "Healthy Snacking" product launch decision
# ============================================================

print("=" * 60)
print("    STORY 6: CANDIDATE'S CHOICE — NUTRI-SCORE ANALYSIS")
print("=" * 60)

print("""
WHY I ADDED THIS:
The client needs to know not just WHERE the Blue Ocean is,
but whether those products are genuinely HEALTHY by an
independent standard. Nutri-Score (A=healthiest, E=worst)
gives us a validated scientific health rating.

This analysis answers: "Are our Blue Ocean products
actually healthy, or just low-sugar coincidentally?"

If Blue Ocean products score A/B on Nutri-Score, we have
strong evidence for a premium health positioning.
This is critical intelligence for Helix CPG Partners'
R&D team before they invest in product development.
""")

# Filter products with Nutri-Score data
df_nutri = df_viz[df_viz['nutriscore_score'].notna()].copy()

# Convert numeric Nutri-Score to letter grade
# Nutri-Score: <=−1 = A, 0-2 = B, 3-10 = C, 11-18 = D, >=19 = E
def score_to_grade(score):
    if score <= -1: return 'A (Best)'
    elif score <= 2: return 'B'
    elif score <= 10: return 'C'
    elif score <= 18: return 'D'
    else: return 'E (Worst)'

df_nutri['nutri_grade'] = df_nutri['nutriscore_score'].apply(score_to_grade)

print(f"📊 Products with Nutri-Score data: {len(df_nutri):,}")
print(f"\n📋 Overall Nutri-Score Distribution:")
print(df_nutri['nutri_grade'].value_counts())

# Blue Ocean vs Oversaturated Nutri-Score comparison
blue_ocean_nutri = df_nutri[
    (df_nutri['sugars_100g'] < sugar_threshold) &
    (df_nutri['proteins_100g'] >= protein_threshold)
]
oversat_nutri = df_nutri[
    (df_nutri['sugars_100g'] >= sugar_threshold) &
    (df_nutri['proteins_100g'] < protein_threshold)
]

print(f"\n🎯 Blue Ocean Nutri-Score (High Protein + Low Sugar):")
blue_grade_dist = blue_ocean_nutri['nutri_grade'].value_counts(normalize=True)*100
print(blue_grade_dist.round(1))

print(f"\n⚠️ Oversaturated Zone Nutri-Score (High Sugar + Low Protein):")
over_grade_dist = oversat_nutri['nutri_grade'].value_counts(normalize=True)*100
print(over_grade_dist.round(1))

# Visualize comparison
fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle("Candidate's Choice: Nutri-Score Health Ratings\nBlue Ocean vs Oversaturated Zone",
             fontsize=14, fontweight='bold')

grade_order = ['A (Best)', 'B', 'C', 'D', 'E (Worst)']
grade_colors = ['#27AE60', '#82E0AA', '#F4D03F', '#E59866', '#E74C3C']

# Blue Ocean grades
blue_vals = [blue_grade_dist.get(g, 0) for g in grade_order]
axes[0].bar(grade_order, blue_vals, color=grade_colors, alpha=0.85, edgecolor='white')
axes[0].set_title('Blue Ocean Products\n(High Protein + Low Sugar)', fontweight='bold')
axes[0].set_ylabel('Percentage of Products (%)')
axes[0].set_ylim(0, 60)
for i, v in enumerate(blue_vals):
    if v > 0:
        axes[0].text(i, v+0.5, f'{v:.1f}%', ha='center', fontweight='bold')

# Oversaturated grades
over_vals = [over_grade_dist.get(g, 0) for g in grade_order]
axes[1].bar(grade_order, over_vals, color=grade_colors, alpha=0.85, edgecolor='white')
axes[1].set_title('Oversaturated Zone\n(Low Protein + High Sugar)', fontweight='bold')
axes[1].set_ylabel('Percentage of Products (%)')
axes[1].set_ylim(0, 60)
for i, v in enumerate(over_vals):
    if v > 0:
        axes[1].text(i, v+0.5, f'{v:.1f}%', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('story6_candidates_choice.png', dpi=150, bbox_inches='tight')
plt.show()

# Nutri-Score by Category heatmap
nutri_cat = df_nutri.groupby(['primary_category', 'nutri_grade']).size().unstack(fill_value=0)
nutri_cat_pct = nutri_cat.div(nutri_cat.sum(axis=1), axis=0) * 100

fig3, ax3 = plt.subplots(figsize=(14, 7))
sns.heatmap(nutri_cat_pct.round(1),
            annot=True, fmt='.1f', cmap='RdYlGn',
            ax=ax3, cbar_kws={'label': '% of Products'})
ax3.set_title("Nutri-Score Health Ratings by Category (%)\nGreen = Healthier Products",
              fontsize=13, fontweight='bold')
ax3.set_xlabel('Nutri-Score Grade')
ax3.set_ylabel('Category')
plt.tight_layout()
plt.savefig('story6_nutriscore_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n✅ Story 6 — Candidate's Choice COMPLETE!")
print("✅ Nutri-Score analysis saved!")

# ============================================================
# CELL 10: Final Summary, Export & Submission Prep
# ============================================================

print("=" * 60)
print("    FINAL SUMMARY — THE SUGAR TRAP MARKET GAP ANALYSIS")
print("    Analyst: Lawrence Koomson | UCC | June 2026")
print("    Client: Helix CPG Partners")
print("=" * 60)

print(f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXECUTIVE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Analysis of 109,564 food products from the Open Food Facts
database reveals a clear and actionable market gap in the
healthy snacking space.

KEY FINDINGS:

1. MARKET LANDSCAPE
   • Total clean products analysed: {len(df):,}
   • Products categorised: {len(df[df['primary_category']!='Uncategorized']):,}
   • Categories identified: 8 high-level buckets

2. THE BLUE OCEAN (High Protein + Low Sugar)
   • {len(blue_ocean):,} products occupy this underserved space
   • Average protein: {blue_ocean['proteins_100g'].mean():.1f}g per 100g
   • Average sugar: {blue_ocean['sugars_100g'].mean():.1f}g per 100g

3. THE OVERSATURATED ZONE (High Sugar + Low Protein)
   • {len(oversaturated):,} products crowd this space
   • 54.1% score E (Worst) on Nutri-Score
   • Dominated by Snacks & Confectionery

4. THE RECOMMENDATION
   • Best category: Dairy & Eggs
   • Target protein: 20.2g per 100g
   • Target max sugar: 4.3g per 100g
   • 2,564 Blue Ocean products validate this gap exists

5. TOP PROTEIN SOURCES FOR R&D TEAM
   • #1 Soy/Soya (30.3% of high-protein products)
   • #2 Peanuts (9.7%)
   • #3 Whey (9.0%)

6. HEALTH VALIDATION (Candidate's Choice)
   • Blue Ocean products: 24.5% score A (Best) on Nutri-Score
   • Oversaturated zone: 54.1% score E (Worst)
   • Blue Ocean = genuinely healthier products ✅
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
""")

# ============================================================
# EXPORT CLEANED DATASET
# ============================================================
print("⏳ Exporting cleaned dataset...")
df.to_csv('cleaned_food_data.csv', index=False)
print(f"✅ Cleaned dataset exported: cleaned_food_data.csv ({len(df):,} rows)")

# Export Blue Ocean subset
blue_ocean_export = df_viz[
    (df_viz['sugars_100g'] < sugar_threshold) &
    (df_viz['proteins_100g'] >= protein_threshold)
].copy()
blue_ocean_export.to_csv('blue_ocean_products.csv', index=False)
print(f"✅ Blue Ocean products exported: blue_ocean_products.csv ({len(blue_ocean_export):,} rows)")

# ============================================================
# CREATE COMPREHENSIVE DASHBOARD FIGURE
# ============================================================
print("\n⏳ Creating comprehensive dashboard figure...")

fig = plt.figure(figsize=(20, 24))
fig.patch.set_facecolor('#F8F9FA')

# Title
fig.text(0.5, 0.98,
         'THE SUGAR TRAP — Market Gap Analysis Dashboard',
         ha='center', va='top', fontsize=20, fontweight='bold', color='#1A252F')
fig.text(0.5, 0.965,
         'Client: Helix CPG Partners | Analyst: Lawrence Koomson, UCC 2026',
         ha='center', va='top', fontsize=12, color='#555555', style='italic')

# ── Chart 1: Category Distribution (top left)
ax1 = fig.add_axes([0.05, 0.74, 0.42, 0.20])
cat_data = df[df['primary_category'] != 'Uncategorized']['primary_category'].value_counts()
colors_c = ['#3498DB','#E74C3C','#2ECC71','#F39C12','#9B59B6','#1ABC9C','#E67E22','#95A5A6']
cat_data.plot(kind='barh', ax=ax1, color=colors_c[:len(cat_data)], alpha=0.85)
ax1.set_title('Products by Category', fontweight='bold', fontsize=12)
ax1.set_xlabel('Number of Products')
ax1.tick_params(axis='y', labelsize=9)

# ── Chart 2: Quadrant pie (top right)
ax2 = fig.add_axes([0.55, 0.74, 0.40, 0.20])
quadrant_counts = [
    len(blue_ocean),
    len(oversaturated),
    len(df_viz[(df_viz['sugars_100g'] < sugar_threshold) &
               (df_viz['proteins_100g'] < protein_threshold)]),
    len(df_viz[(df_viz['sugars_100g'] >= sugar_threshold) &
               (df_viz['proteins_100g'] >= protein_threshold)])
]
quadrant_labels = [
    f'Blue Ocean\n{len(blue_ocean):,}',
    f'Oversaturated\n{len(oversaturated):,}',
    f'Low Both\n{len(df_viz[(df_viz["sugars_100g"]<sugar_threshold)&(df_viz["proteins_100g"]<protein_threshold)]):,}',
    f'High Both\n{len(df_viz[(df_viz["sugars_100g"]>=sugar_threshold)&(df_viz["proteins_100g"]>=protein_threshold)]):,}'
]
ax2.pie(quadrant_counts,
        labels=quadrant_labels,
        colors=['#27AE60','#E74C3C','#3498DB','#F39C12'],
        autopct='%1.1f%%', startangle=90,
        textprops={'fontsize': 9})
ax2.set_title('Market Quadrant Distribution', fontweight='bold', fontsize=12)

# ── Chart 3: Nutrient Matrix Scatter (middle — large)
ax3 = fig.add_axes([0.05, 0.42, 0.90, 0.28])
for cat in df_viz['primary_category'].unique():
    if cat == 'Uncategorized':
        continue
    mask = df_sample['primary_category'] == cat
    subset = df_sample[mask]
    if len(subset) > 0:
        ax3.scatter(subset['sugars_100g'], subset['proteins_100g'],
                   c=color_map.get(cat, '#95A5A6'),
                   label=cat, alpha=0.35, s=15, edgecolors='none')

ax3.axvline(x=sugar_threshold, color='red', linestyle='--', linewidth=2, alpha=0.8)
ax3.axhline(y=protein_threshold, color='green', linestyle='--', linewidth=2, alpha=0.8)
from matplotlib.patches import Rectangle
rect = Rectangle((0, protein_threshold), sugar_threshold,
                 100-protein_threshold, linewidth=2,
                 edgecolor='#27AE60', facecolor='#27AE60', alpha=0.08)
ax3.add_patch(rect)
ax3.text(sugar_threshold/2, 85,
         '🎯 BLUE OCEAN\nHigh Protein + Low Sugar',
         ha='center', fontsize=12, fontweight='bold', color='#27AE60',
         bbox=dict(boxstyle='round,pad=0.4', facecolor='white', alpha=0.9))
ax3.text(70, 3, '⚠️ OVERSATURATED\nHigh Sugar + Low Protein',
         ha='center', fontsize=10, color='#E74C3C', style='italic')
ax3.set_xlabel('Sugar per 100g (g)', fontsize=12, fontweight='bold')
ax3.set_ylabel('Protein per 100g (g)', fontsize=12, fontweight='bold')
ax3.set_title('The Nutrient Matrix: Sugar vs Protein\n"Finding the Blue Ocean in the Snack Aisle"',
              fontsize=13, fontweight='bold')
ax3.set_xlim(0, 100)
ax3.set_ylim(0, 100)
ax3.legend(bbox_to_anchor=(1.01, 1), loc='upper left', fontsize=8)
ax3.grid(True, alpha=0.3)

# ── Chart 4: Hidden Gem — Top protein sources (bottom left)
ax4 = fig.add_axes([0.05, 0.20, 0.42, 0.18])
top_sources = protein_series.head(6)
bar_colors = ['#E74C3C','#E74C3C','#E74C3C','#3498DB','#3498DB','#3498DB']
top_sources.plot(kind='bar', ax=ax4, color=bar_colors, alpha=0.85, edgecolor='white')
ax4.set_title('Hidden Gem: Top Protein Sources\n(Red = Top 3)', fontweight='bold', fontsize=11)
ax4.set_ylabel('High-Protein Products')
ax4.tick_params(axis='x', rotation=45, labelsize=9)

# ── Chart 5: Nutri-Score comparison (bottom right)
ax5 = fig.add_axes([0.55, 0.20, 0.40, 0.18])
x = np.arange(len(grade_order))
width = 0.35
blue_vals_plot = [blue_grade_dist.get(g, 0) for g in grade_order]
over_vals_plot = [over_grade_dist.get(g, 0) for g in grade_order]
ax5.bar(x - width/2, blue_vals_plot, width, label='Blue Ocean', color='#27AE60', alpha=0.85)
ax5.bar(x + width/2, over_vals_plot, width, label='Oversaturated', color='#E74C3C', alpha=0.85)
ax5.set_xticks(x)
ax5.set_xticklabels(grade_order, fontsize=9)
ax5.set_title("Candidate's Choice: Nutri-Score\nBlue Ocean vs Oversaturated", fontweight='bold', fontsize=11)
ax5.set_ylabel('% of Products')
ax5.legend(fontsize=9)

# ── Key Insight Box (bottom)
ax6 = fig.add_axes([0.05, 0.03, 0.90, 0.14])
ax6.axis('off')
insight = (
    '🎯  KEY INSIGHT FOR HELIX CPG PARTNERS\n\n'
    '"Based on the data, the biggest market opportunity is in Dairy & Eggs,\n'
    'specifically targeting products with 20.2g of protein and less than 4.3g of sugar."\n\n'
    '📊 Evidence: 11,869 Blue Ocean products vs 11,946 Oversaturated products — the gap is real and measurable.\n'
    '🏆 Top R&D Protein Sources: #1 Soy/Soya (30.3%)  •  #2 Peanuts (9.7%)  •  #3 Whey (9.0%)\n'
    '✅ Health Validation: Blue Ocean products score A/B on Nutri-Score — genuinely healthy, not just low-sugar.'
)
ax6.text(0.5, 0.5, insight, transform=ax6.transAxes,
         fontsize=12, ha='center', va='center', linespacing=1.9,
         bbox=dict(boxstyle='round,pad=1.0', facecolor='#EBF5FB',
                  edgecolor='#2E86C1', linewidth=3))

plt.savefig('AmaliTech_Complete_Dashboard.png', dpi=150,
            bbox_inches='tight', facecolor='#F8F9FA')
plt.show()
print("✅ Complete dashboard saved as AmaliTech_Complete_Dashboard.png!")
print("\n🎉 ALL STORIES COMPLETE — READY FOR SUBMISSION!")

# ============================================================
# CELL 11: Final Checklist & Instructions
# ============================================================

print("=" * 60)
print("    SUBMISSION PREPARATION CHECKLIST")
print("=" * 60)

print("""
✅ COMPLETED:
   Story 1 — Data Ingestion & Clean Up ✅
   Story 2 — Category Wrangler (8 categories) ✅
   Story 3 — Nutrient Matrix Visualization ✅
   Story 4 — The Recommendation ✅
   Story 5 — Hidden Gem (Top protein sources) ✅
   Story 6 — Candidate's Choice (Nutri-Score) ✅

📁 FILES GENERATED:
   • story1_distributions.png
   • story2_categories.png
   • story3_nutrient_matrix.png
   • story4_recommendation.png
   • story4_key_insight_box.png
   • story5_hidden_gem.png
   • story6_candidates_choice.png
   • story6_nutriscore_heatmap.png
   • AmaliTech_Complete_Dashboard.png
   • cleaned_food_data.csv
   • blue_ocean_products.csv

📋 NEXT STEPS:
   1. Download this notebook as .ipynb
      File → Download → Download .ipynb

   2. Download notebook as HTML
      File → Download → Download .html

   3. Download all PNG files from Colab files panel

   4. Upload to your GitHub repo:
      - AmaliTech_Market_Gap_Analysis.ipynb
      - AmaliTech_Market_Gap_Analysis.html
      - AmaliTech_Complete_Dashboard.png
      - All story PNG files
      - DO NOT upload the CSV dataset files!

   5. Update README.md with Executive Summary

   6. Fill the submission form:
      https://forms.office.com/e/heitZ9PP7y

🎉 READY FOR SUBMISSION!
""")